package Rules.Excel.intentions;

/*Generated by MPS */

import jetbrains.mps.intentions.AbstractIntentionDescriptor;
import jetbrains.mps.openapi.intentions.IntentionFactory;
import java.util.Collection;
import jetbrains.mps.openapi.intentions.IntentionExecutable;
import jetbrains.mps.openapi.intentions.Kind;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.openapi.editor.EditorContext;
import java.util.Collections;
import jetbrains.mps.intentions.AbstractIntentionExecutable;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.openapi.intentions.IntentionDescriptor;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SConcept;

public final class newRuleCollection_Intention extends AbstractIntentionDescriptor implements IntentionFactory {
  private Collection<IntentionExecutable> myCachedExecutable;
  public newRuleCollection_Intention() {
    super(Kind.NORMAL, true, new SNodePointer("r:9da01424-4e95-4488-a48f-23bedeeb1a64(Rules.Excel.intentions)", "6626895832075548752"));
  }
  @Override
  public String getPresentation() {
    return "newRuleCollection";
  }
  @Override
  public boolean isApplicable(final SNode node, final EditorContext editorContext) {
    return true;
  }
  @Override
  public boolean isSurroundWith() {
    return false;
  }
  public Collection<IntentionExecutable> instances(final SNode node, final EditorContext context) {
    if (myCachedExecutable == null) {
      myCachedExecutable = Collections.<IntentionExecutable>singletonList(new IntentionImplementation());
    }
    return myCachedExecutable;
  }
  /*package*/ final class IntentionImplementation extends AbstractIntentionExecutable {
    public IntentionImplementation() {
    }
    @Override
    public String getDescription(final SNode node, final EditorContext editorContext) {
      return "New Rule Group";
    }
    @Override
    public void execute(final SNode node, final EditorContext editorContext) {
      SLinkOperations.addNewChild(node, LINKS.commands$hK3T, CONCEPTS.RuleCollection$6S);
    }
    @Override
    public IntentionDescriptor getDescriptor() {
      return newRuleCollection_Intention.this;
    }
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink commands$hK3T = MetaAdapterFactory.getContainmentLink(0x17e7b90aaaca44c7L, 0xaaaa8155bb498bd7L, 0x7e19241b9e5efb76L, 0x7e19241b9e5efb7fL, "commands");
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept RuleCollection$6S = MetaAdapterFactory.getConcept(0x8c4b72ae776424aL, 0xb5c9f314339ec802L, 0x5bf776a602542535L, "Rules.Excel.structure.RuleCollection");
  }
}
