package Rule3.sandbox.basic;

/*Generated by MPS */


public class Product {
  private String type;
  private int discount;

  public String getType() {
    return type;
  }
  public void setDiscount(int discount) {
    discount = discount;
  }

}
