package Rules2.sandbox.uva;

/*Generated by MPS */


public class Course {
  private String name;
  public String getName() {
    return name;
  }
  private int ects;
  public int getEcts() {
    return ects;
  }

}
