package Rules2.sandbox.uva;

/*Generated by MPS */

import java.util.List;

public class Student {
  private long id;
  public long getId() {
    return id;
  }
  private Program program;
  public Program getProgram() {
    return program;
  }
  private List<Result> results;
  public List<Result> getResults() {
    return results;
  }
  private int weightedAverage;
  public int getWeightedAverage() {
    return weightedAverage;
  }
  private int yearsStudied;
  public int getYearsdied() {
    return yearsStudied;
  }
  private boolean cumlaude;
  public void setCumlaude(boolean cumlaude) {
    this.cumlaude = cumlaude;
  }
}
