@startuml
	skinparam linetype polyline 
    skinparam ActivityFontSize 16
    skinparam ArrowFontSize 16

	partition "Working Memory" {
        === F1 === --> "Assert fact" as assert
        === F1 === --> "Modify fact" as modify
        === F1 === --> "Retract fact" as retract
        assert --> === F2 ===
        modify --> === F2 ===
        retract --> === F2 ===
    }

    (*) --> assert

    partition "Pattern Matcher" {
        === F2 === --> "Rete-OO algorithm" as algo 
        
    }

    "Production Rules" -left-> algo

    partition "Agenda" {
        ConflictResolver --> "Selected Rules"
        algo --> "Selected Rules" 
 
    }

    if "A rule\nis selected" then
        -right->[Yes] "Fire Rule"
        if "Rule specifies Exit" then
            -up->[Yes] (*)
        else 
            -up->[No] === F1 ===
        endif
    else
        --up->[No] (*)
    endif

@enduml