package Rules.Excel2.editor;

/*Generated by MPS */


public final class HeaderValue {
  private final String fact;
  private final String property;
  private final String restriction;
  public HeaderValue(String fact, String property, String restriction) {
    this.fact = fact;
    this.property = property;
    this.restriction = restriction;
  }
  public String getFact() {
    return fact;
  }
  public String getProperty() {
    return property;
  }
  public String getRestriction() {
    return restriction;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null) {
      return false;
    }
    if (getClass() != o.getClass()) {
      return false;
    }

    HeaderValue headerValue = (HeaderValue) o;

    return fact.equals(headerValue.fact) && property.equals(headerValue.property) && restriction.equals(headerValue.restriction);
  }

  @Override
  public int hashCode() {
    return 31 * fact.hashCode() + property.hashCode() + restriction.hashCode();
  }
}
