@startgantt
printscale weekly
Project starts the 10th of february 2021
[Projectional LWB mapping] lasts 35 days
Then [projectional interviews] lasts 35 days
[Design projections] lasts 28 days and starts 1 week after [projectional interviews]'s start

[Implementing Drools in MPS] lasts 67 days
Then [Building Alternative Projections] lasts 61 days
Then [Finalize project] lasts 4 weeks

[projectional interviews] -> [Building Alternative Projections]


[Defend project] happens 25th july 2021

@endgantt