package Sudoku;

/*Generated by MPS */


public class Setting {
  private int rowNo;
  private int colNo;
  private Integer value;

  public Setting(int row, int col, Integer value) {
    this.rowNo = row;
    this.colNo = col;
    this.value = value;
  }

  public int getRowNo() {
    return rowNo;
  }

  public int getColNo() {
    return colNo;
  }

  public Integer getValue() {
    return value;
  }
}
