package Rules2.behavior;

/*Generated by MPS */

import jetbrains.mps.core.aspects.behaviour.BaseBHDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.core.aspects.behaviour.api.SMethod;
import jetbrains.mps.core.aspects.behaviour.SMethodBuilder;
import jetbrains.mps.core.aspects.behaviour.SJavaCompoundTypeImpl;
import jetbrains.mps.core.aspects.behaviour.SModifiersImpl;
import jetbrains.mps.core.aspects.behaviour.AccessPrivileges;
import java.util.List;
import java.util.Arrays;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.core.aspects.behaviour.api.SConstructor;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.core.aspects.behaviour.api.BHMethodNotFoundException;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import org.jetbrains.mps.openapi.language.SConcept;

public final class MultiRestriction__BehaviorDescriptor extends BaseBHDescriptor {
  private static final SAbstractConcept CONCEPT = MetaAdapterFactory.getConcept(0x17e7b90aaaca44c7L, 0xaaaa8155bb498bd7L, 0x2bdd8885e32f3d74L, "Rules2.structure.MultiRestriction");

  public static final SMethod<String> toString_id6Y4UEk_yGyR = new SMethodBuilder<String>(new SJavaCompoundTypeImpl(String.class)).name("toString").modifiers(SModifiersImpl.create(8, AccessPrivileges.PUBLIC)).concept(CONCEPT).id("6Y4UEk_yGyR").build();
  public static final SMethod<String> toString_id6Y4UEk_yGFN = new SMethodBuilder<String>(new SJavaCompoundTypeImpl(String.class)).name("toString").modifiers(SModifiersImpl.create(8, AccessPrivileges.PUBLIC)).concept(CONCEPT).id("6Y4UEk_yGFN").build();

  private static final List<SMethod<?>> BH_METHODS = Arrays.<SMethod<?>>asList(toString_id6Y4UEk_yGyR, toString_id6Y4UEk_yGFN);

  private static void ___init___(@NotNull SNode __thisNode__) {
  }

  /*package*/ static String toString_id6Y4UEk_yGyR(@NotNull SNode __thisNode__) {
    String lhs = (SNodeOperations.isInstanceOf(SLinkOperations.getTarget(__thisNode__, LINKS.lhsrestriction$aVrh), CONCEPTS.MultiRestriction$y) ? "(" + IMultiRestrictionable__BehaviorDescriptor.toString_id6Y4UEk_yGFN.invoke(SLinkOperations.getTarget(__thisNode__, LINKS.lhsrestriction$aVrh)) + ")" : IMultiRestrictionable__BehaviorDescriptor.toString_id6Y4UEk_yGFN.invoke(SLinkOperations.getTarget(__thisNode__, LINKS.lhsrestriction$aVrh)));
    String rhs = (SNodeOperations.isInstanceOf(SLinkOperations.getTarget(__thisNode__, LINKS.rhsrestriction$eztI), CONCEPTS.MultiRestriction$y) ? "(" + IMultiRestrictionable__BehaviorDescriptor.toString_id6Y4UEk_yGFN.invoke(SLinkOperations.getTarget(__thisNode__, LINKS.rhsrestriction$eztI)) + ")" : IMultiRestrictionable__BehaviorDescriptor.toString_id6Y4UEk_yGFN.invoke(SLinkOperations.getTarget(__thisNode__, LINKS.rhsrestriction$eztI)));


    return lhs + " " + MultiRestrictionOperator__BehaviorDescriptor.toString_id6Y4UEk_yG_j.invoke(SLinkOperations.getTarget(__thisNode__, LINKS.operator$dEUX)) + " " + rhs;
  }
  /*package*/ static String toString_id6Y4UEk_yGFN(@NotNull SNode __thisNode__) {
    return Restriction__BehaviorDescriptor.toString_id6Y4UEk_yGyR.invoke(__thisNode__);
  }

  /*package*/ MultiRestriction__BehaviorDescriptor() {
  }

  @Override
  protected void initNode(@NotNull SNode node, @NotNull SConstructor constructor, @Nullable Object[] parameters) {
    ___init___(node);
  }

  @Override
  protected <T> T invokeSpecial0(@NotNull SNode node, @NotNull SMethod<T> method, @Nullable Object[] parameters) {
    int methodIndex = BH_METHODS.indexOf(method);
    if (methodIndex < 0) {
      throw new BHMethodNotFoundException(this, method);
    }
    switch (methodIndex) {
      case 0:
        return (T) ((String) toString_id6Y4UEk_yGyR(node));
      case 1:
        return (T) ((String) toString_id6Y4UEk_yGFN(node));
      default:
        throw new BHMethodNotFoundException(this, method);
    }
  }

  @Override
  protected <T> T invokeSpecial0(@NotNull SAbstractConcept concept, @NotNull SMethod<T> method, @Nullable Object[] parameters) {
    int methodIndex = BH_METHODS.indexOf(method);
    if (methodIndex < 0) {
      throw new BHMethodNotFoundException(this, method);
    }
    switch (methodIndex) {
      default:
        throw new BHMethodNotFoundException(this, method);
    }
  }

  @NotNull
  @Override
  public List<SMethod<?>> getDeclaredMethods() {
    return BH_METHODS;
  }

  @NotNull
  @Override
  public SAbstractConcept getConcept() {
    return CONCEPT;
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink lhsrestriction$aVrh = MetaAdapterFactory.getContainmentLink(0x17e7b90aaaca44c7L, 0xaaaa8155bb498bd7L, 0x2bdd8885e32f3d74L, 0x2bdd8885e32f3d75L, "lhsrestriction");
    /*package*/ static final SContainmentLink rhsrestriction$eztI = MetaAdapterFactory.getContainmentLink(0x17e7b90aaaca44c7L, 0xaaaa8155bb498bd7L, 0x2bdd8885e32f3d74L, 0x2bdd8885e32f3de0L, "rhsrestriction");
    /*package*/ static final SContainmentLink operator$dEUX = MetaAdapterFactory.getContainmentLink(0x17e7b90aaaca44c7L, 0xaaaa8155bb498bd7L, 0x2bdd8885e32f3d74L, 0x2bdd8885e32f3d97L, "operator");
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept MultiRestriction$y = MetaAdapterFactory.getConcept(0x17e7b90aaaca44c7L, 0xaaaa8155bb498bd7L, 0x2bdd8885e32f3d74L, "Rules2.structure.MultiRestriction");
  }
}
