package Sudoku;

/*Generated by MPS */


public class CellRow extends CellFile {

  public CellRow(int number) {
    super(number);
  }

  @Override
  public String toString() {
    return "Row " + getNumber() + ": " + super.toString();
  }
}
