package Sudoku;

/*Generated by MPS */


public class Counter {
  private int count;

  public Counter(int init) {
    this.count = init;
  }
  public int getCount() {
    return count;
  }
  public void setCount(int count) {
    this.count = count;
  }
}
