package Rules2.sandbox.demo;

/*Generated by MPS */

import java.util.List;

public class Program {
  private Faculty faculty;
  public Faculty getFaculty() {
    return faculty;
  }
  private List<Course> courses;
  public List<Course> getCourses() {
    return courses;
  }
}
