package Rules2.behavior;

/*Generated by MPS */

import jetbrains.mps.core.aspects.behaviour.BaseBehaviorAspectDescriptor;
import jetbrains.mps.core.aspects.behaviour.api.BHDescriptor;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public final class BehaviorAspectDescriptor extends BaseBehaviorAspectDescriptor {
  private final BHDescriptor myRuleStatement__BehaviorDescriptor = new RuleStatement__BehaviorDescriptor();
  private final BHDescriptor myRuleVariable__BehaviorDescriptor = new RuleVariable__BehaviorDescriptor();
  private final BHDescriptor myFactProperty__BehaviorDescriptor = new FactProperty__BehaviorDescriptor();
  private final BHDescriptor myFactPropertyAccessorRef__BehaviorDescriptor = new FactPropertyAccessorRef__BehaviorDescriptor();
  private final BHDescriptor myRuleAttributes__BehaviorDescriptor = new RuleAttributes__BehaviorDescriptor();

  public BehaviorAspectDescriptor() {
  }

  @Nullable
  public BHDescriptor getDescriptor(@NotNull SAbstractConcept concept) {
    SAbstractConcept cncpt = concept;
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return myFactProperty__BehaviorDescriptor;
      case 1:
        return myFactPropertyAccessorRef__BehaviorDescriptor;
      case 2:
        return myRuleAttributes__BehaviorDescriptor;
      case 3:
        return myRuleStatement__BehaviorDescriptor;
      case 4:
        return myRuleVariable__BehaviorDescriptor;
      default:
    }
    return null;
  }
  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x17e7b90aaaca44c7L, 0xaaaa8155bb498bd7L, 0x7e19241b9e793468L), MetaIdFactory.conceptId(0x17e7b90aaaca44c7L, 0xaaaa8155bb498bd7L, 0x7e19241b9e7d398bL), MetaIdFactory.conceptId(0x17e7b90aaaca44c7L, 0xaaaa8155bb498bd7L, 0x7e19241b9eb25ea0L), MetaIdFactory.conceptId(0x17e7b90aaaca44c7L, 0xaaaa8155bb498bd7L, 0x7e19241b9e61793cL), MetaIdFactory.conceptId(0x17e7b90aaaca44c7L, 0xaaaa8155bb498bd7L, 0x7e19241b9e61c8d6L)).seal();
}
